import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import ReduxProvider from "@/components/providers/ReduxProvider";

// ✅ Add Marathi font
const notoSans = Noto_Sans({
	variable: "--font-devanagari",
	subsets: ["devanagari"],
	weight: ["400", "500", "600", "700"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="mr" className={`${notoSans.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col bg-white text-slate-900">
				<ReduxProvider>
					<AuthProvider>
						{children}
					</AuthProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
