import { Noto_Sans_Devanagari } from "next/font/google";
import "./globals.css";

// ✅ Add Marathi font
const devanagari = Noto_Sans_Devanagari({
	variable: "--font-devanagari",
	subsets: ["devanagari"],
	weight: ["400", "500", "600", "700"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="mr" className={`${devanagari.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col bg-white text-slate-900">
				{children}
			</body>
		</html>
	);
}